import Footer from "@/components/Footer/Footer";
import Hero from "@/components/Hero/Hero";
import TechStack from "@/components/TechStack/TechStack";
import Terminal from "@/components/Terminal/Terminal";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Asep Saepudin | Fullstack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/profile.png" />
      </Head>

      <div className="relative max-w-[1920px] m-auto ">
        <div className="w-full px-5 py-10 lg:h-[80vh] md:mt-[40px] md:px-10 lg:mt-[80px]">
          <Hero />
        </div>

        <div className="px-3 md:mt-[40px] md:px-10 lg:mt-[80px] h-[90vh]">
          <Terminal />
        </div>

        <div className="mt-10 md:mt-[100px] w-full left-0">
          <TechStack />
        </div>

        <div className="px-5 mb-10 mt-10 md:mt-[40px] lg:mt-[80px]">
          <Footer />
        </div>
      </div>
    </>
  );
}
